#!/usr/bin/env php
<?php

$env_info = array();

if ($_SERVER['OPENSHIFT_MYSQL_DB_USERNAME'] || TRUE) {
  $env_info['databases']['default']['default'] = array(
    'driver' => 'mysql',
    'database' => $_SERVER['OPENSHIFT_APP_NAME'],
    'username' => $_SERVER['OPENSHIFT_MYSQL_DB_USERNAME'],
    'password' => $_SERVER['OPENSHIFT_MYSQL_DB_PASSWORD'],
    'host' => $_SERVER['OPENSHIFT_MYSQL_DB_HOST'],
    'prefix' => '',
  );
}

// @TODO: Set up memcached.
// @TODO: Set up Redis.
// @TODO: Set up Varnish.

printf("PRESSFLOW_SETTINGS=%s", json_encode($env_info));
echo "YO=dawg";
